# 실행에서 제외할 룰 식별자들
disabled_rules:
  - type_name
  - trailing_whitespace
  - identifier_name
  - nesting

# 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 `--path`는 무시됨
included:

# 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음
excluded:
  - Pods

line_length: 120

force_cast: warning
force_try:
  severity: warning
